### ISSUE TITLE
Définition du projet

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#1]
## Description   
Créer les contours du projet + maquette du MVP. 

## TODO
- [x] Créer un `README.md` avec les obejctifs du MVP 
  - [x] Quel est le but premier du projet ?
  - [x] Quels features doit inclure le projet en premier lieu ?
  - [x] Quels outils seront necessaires pour le mettre en place ? (comprendre outils techniques)
