### ISSUE TITLE
Finalisation gestion metas

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#128]
## Description 
Finalisation de la première partie concernant le modèle de `Page`

## TODO
- [x]  Ajouter la balise `hreflang`
- [x] Clean le modèle de `Page`
- [x] Vérifier les balises et rajouter si besoin d'autres balises importantes
