### ISSUE TITLE
Page de Registration

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#159]
## Description     
Création de la page de création de compte utilisateur

## TODO   
- [x] Faire le tour des traductions
- [x] Créer les images og
- [x] Reprendre le favicon
- [x] Clean le sass
- [x] Redécouper proprement la suite
- [x] Valider l'username en lowercase 
- [x] Reprendre les emails + trads
- [x] Réfléchir au style global du site
- [x] Faire une recherche sur les pages d'inscriptions à la mode
- [x] Créer la `Cms\Page`
- [x] revoir la charte graphique, cf  https://search.muz.li/ODFkNDg5MWIz
- [x] Trouver une illustration
- [x] Trouver un logo
- [x] Compresser les images
- [x] Ajouter le bouton dans la navbar
- [x] Créer la favicon
- [x] Ajouter les trads en francais
- [x] Ajouter un bouton `teaser` quand logué
