### ISSUE TITLE
Reintialisation de mot de passe

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#166]
## Description    
Créer une méthode pour réinitialiser son mot de passe.

## TODO   
- [x] Installer `SymfonyCast/reset-password` bundle 
- [x] Setup les différentes vues / forms et tester le système
- [x] Tester le comportement des différents cas d'erreurs
- [x] Créer la page `Cms\Page`
