### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#23]
## Description    
l'internationalisation du projet est une feature qui doit être prise en compte en amont du projet, il me semble important que la version Beta la prenne en charge.

## TODO   
- [x] R&D sur la meilleure façon de gérer l'intl sur un projet symfony
- [x] mettre en place des fichiers de traductions pour la home et la page projet en FR
- [x] localiser l'utilisateur et lui donner la possibilité de changer de langue 
- [ ] traduire les pages en EN
  - [x] Homepage
  - [ ] Le projet
- [x] Trouver une solution pour traduire la route également (voir https://phrase.com/blog/posts/symfony-4-i18n/)
- [x] Trouver une solution pour extraire les labels de formulaire
- [x] Revoir l'intégration du toggle responsive 
- [x] corriger notified notified sur home

## Recherche
- Il esxiste un tag à placer dans la balise head pour indiquer les différentes langues prises en charge `<link rel="alternate" hreflang="es" href="https://www.thetrainline.com/es">`
- - Voir bests practices https://php-translation.readthedocs.io/en/latest/best-practice/
