### ISSUE TITLE
Configuration du mailer

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#24]
## Description   
Mettre en place une boite mail + configuration du mailer pour l'envoie de notification.

## TODO     
- [x] configuration d'une boite mail sur OVH : `erwan@mybicyclejourney.com`
- [x] configuration du mailer symfony
- [x] à la création d'un `EarlyBird` :   
  - [x] Création d'un événement lors de l'enregistrement d'un early bird
  - [x]  envoie d'une notification au prospect
  - [x] envoie d'une notification à moi-même
- [x] Modifier le `Procfile` pour restart le worker suivant la doc SF
