### ISSUE TITLE
Meilleur gestion SEO

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#64]
## Description 
Création d'un modèle administrable pour décrire les informations essentielles de chaque page du site.   
Il sera utilisé pour :
- Construire le sitemap 
- Construire les breadcrumbs
- Rédiger les données SEO dynamiquement

## TODO
- [x] Reprendre le modèle `Page` et supprimer les metas + créer des value objects plus proche du métier et moins techniques : `SocialMedia`
- [x] Corriger le responsive du menu sur la page le projet (banner title passe par dessus)
- [x] Traduire les metas en anglais 
- [x] Créer un service pour gérer les `Page` manquante et ne pas throw d'exception + ajouter l'information des autres langues disponibles
- [x]  Revoir le rendu de la page en Twig & ajouter les balises hreflang + canonical
- [x] Passer le cookie consent en version EN

## Annexes
- Utilisation des balises : https://smartkeyword.io/en/seo-on-page-title-tag/
