### ISSUE TITLE
Social share

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#69]
## Description   
Le site a vocation à être partagé sur les reseaux sociaux, il faut donc que celui ci réponde aux recommandation des différents sites.

## TODO   
- [x] Faire une R&D sur les bones pratiques des principaux sites de reseau sociaux (`Facebook`, `Twitter`, `Instagram`) + reseaux sociaux propres à l'univers du vélo (TBD).
- [x] Mettre en place les améliorations necessaires dans le modèle `Seo\Page`
- [x] Créer les assets pour les pages `homepage` & `the_project`.
