### ISSUE TITLE
Configuration serveur + stratégie de déploiement

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#7]
## Description   
Configurer Heroku pour pouvoir host l'application et deployer facilement.

**Objectif**  : avoir une stratégie de déploiement simple et une premiere version du site online.

## TODO   
- [x] Créer les dynos necessaires
- [x] Définir la stratégie de déploiement et la mettre en place
- [x] Configurer le nom de domaine
