### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#70]
## Description   
Créer un sitemap + méthode pour le tenir à jour.

## TODO   
- [x] Créer le `sitemap.xml`
- [x] Envoyer les infos sur la Google Search Console
- [ ] Faire le tour des balises à rajouter 
  - [ ] `locale alternate`
