### ISSUE TITLE
Création de la home

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#8]
## BLOCKED   
requires : 
- https://github.com/erwan-haquet/mybicyclejourney/issues/19

# Description   
Création d'une première homepage basique sur laquelle il doit être possible de :   
- Enregistrer son email pour être tenu au courant des avancés
- Comprendre via quelques lignes les objectifs du projet

## TODO    
- [x] Mettre en place SASS et définir une charte graphique 
- [x] Créer une base de donnée et une première entité `marketing_early_bird`
- [x] Créer le controller `home`
- [x] Trouver une image en 1440 x 740
- [x] Metre un favicon au top 🚴
- [x] Intégrer le formulaire `stay tuned` 
  - [x]  Ajouter un flash message pour remercier
  - [x] Clear le form après soumission
  - [x] Ne pas pouvoir ajouter 2 x le même email
- [x] Améliorer l'ui + valider le responsive

![PXL_20220523_143020777](https://user-images.githubusercontent.com/12082224/169842833-1fa41557-339e-434e-a4b6-febecaea4915.jpg)
