### ISSUE TITLE
Guideline Templating 

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#82]
## Description. 
Le Templating actuel est un peu sommaire et risque de ne pas être maintenable a l'avenir, il faudrait faire un peu de R&D puis mettre en place une guideline.

## TODO
- [x] R&D bests practices `twig` / `html` + mise en place sur le projet https://github.com/erwan-haquet/mybicyclejourney/pull/88
- [x] R&D bests practices `sass` + mise en place sur le projet. https://github.com/erwan-haquet/mybicyclejourney/pull/90, cf. https://sass-guidelin.es/fr/#architecture
- [x] Clean l'intégration de la `homepage` & des `flash_messages`
- [x] `mark` ne prend plus en compte la couleur du texte, qui ne ressort plus assez.
- [x] la redirection http => https://wwww. Ne fonctionne plus
